### ISSUE TITLE
setup.py missing?

### ISSUE THREAD

**Issue by AstroJLo** [tvwenger/kd#1]
Hi @tvwenger - thanks for taking the time to upload your KD code to Github. I'm keen to use it ASAP, but i can't seem to seem to install it; as a setup.py file isn't included. Is there any chance you could upload one?

**Comment by tvwenger** [comment]
@AstroJLo Done! I tested it in a virtual environment, but let me know how it works for you.

**Comment by AstroJLo** [comment]
Hi Trey,


Thank you very much for your prompt response. I can now confirm that i have the code correctly running on my mac :)


One quick question: when i run the monte-carlo kinematic distance estimate, i don't get the same output as that mentioned in the code (see attached pic). Can i just confirm that is simply due to the stochastic nature of the Monte Carlo code?


Looking forward to hearing from you.


Best regards,


##########################
John Alexander Pena Lopez
PhD student in Astrophysics
UNSW Sydney
CSIRO Astronomy and Space Science
##########################
________________________________

**Comment by tvwenger** [comment]
@AstroJLo Yes, that is just the nature of Monte Carlo randomness. You'll notice that the results you get are within the uncertainties of what I got. If you increase the number of samples to about 10,000, you'll get the same results each time. 

You can ensure that the exact results are reproduceable by setting the random seed in numpy before doing anything:

```python
import numpy as np
np.random.seed(1234) # random seed number can be anything
```
